### all categories
GET http://localhost:8081/api/v1/books-categories
Authorization: Basic admin2 Raz12345!

### all categories page
GET http://localhost:8081/api/v1/books-categories/page?name=dr
Authorization: Basic admin2 Raz12345!

### add category
POST http://localhost:8081/api/v1/books-categories/add
Authorization: Basic admin2 Raz12345!
Content-Type: application/json

{
  "name": "gfdgdfg"
}

### get category by id
GET http://localhost:8081/api/v1/books-categories/202
Authorization: Basic admin2 Raz12345!

### update category by id
PUT http://localhost:8081/api/v1/books-categories/202
Authorization: Basic admin2 Raz12345!
Content-Type: application/json

{
  "name": "drama"
}

### delete category by id
DELETE http://localhost:8081/api/v1/books-categories/202
Authorization: Basic admin2 Raz12345!