### ALL BOOKS
GET http://localhost:8081/online-library/books
Authorization: Basic simple 666666Raz!

### get books page
GET http://localhost:8081/online-library/books/page?pageSize=4&pageNo=0&sortBy=author&sortDir=asc
Authorization: Basic simple 666666Raz!

### add book
POST http://localhost:8081/online-library/books/add
Content-Type: application/json
Authorization: Basic pro 666666Raz!

{
  "name": "name1",
  "location": "-1hgf2",
  "author": "ra4 2344234"
}

###get book by id
GET http://localhost:8081/online-library/books/1
Authorization: Basic pro 666666Raz!

### update book - location
PUT http://localhost:8081/online-library/books/1
Content-Type: application/json
Authorization: Basic pro 666666Raz!

{
  "location": "floor -3"
}

### delete book by id
DELETE http://localhost:8081/online-library/books/4
Authorization: Basic pro 666666Raz!