### ALL BOOKS
GET http://localhost:8081/online-library/books
Authorization: Basic admin 666666Raz!

### get books page
GET http://localhost:8081/online-library/books/page?name=test&publishYear=1995
Authorization: Basic admin 666666Raz!

### add book
POST http://localhost:8081/online-library/books/add
Content-Type: application/json
Authorization: Basic admin 666666Raz!

{
  "name": "test",
  "author": "raz goanizada",
  "description": "fsafdsakfabsfkasbfaskfb dslfdndlfsdnfldsfnsfslfn dlagnalgagnsg",
  "bookcase": "158",
  "bookCategoriesName": "drama",
  "publishYear": "1998"
}

###get book by id
GET http://localhost:8081/online-library/books/1
Authorization: Basic admin 666666Raz!

### update book
PUT http://localhost:8081/online-library/books/1
Content-Type: application/json
Authorization: Basic admin 666666Raz!

{
  "bookCategoriesName": "drama",
  "bookcase": "158",
  "description": "fsafdsakfabsfkasbfaskfb dslfdndlfsdnfldsfnsfslfn dlagnalgagnsg"
}

### delete book by id
DELETE http://localhost:8081/online-library/books/1
Authorization: Basic admin 666666Raz!