### all categories
GET http://localhost:8081/online-library/books-categories
Authorization: Basic admin Password6!

### all categories page
GET http://localhost:8081/online-library/books-categories/page?name=dr
Authorization: Basic admin Password6!

### add category
POST http://localhost:8081/online-library/books-categories/add
Authorization: Basic admin Password6!
Content-Type: application/json

{
  "name": "fdf"
}

### get category by id
GET http://localhost:8081/online-library/books-categories/202
Authorization: Basic admin Password6!

### update category by id
PUT http://localhost:8081/online-library/books-categories/202
Authorization: Basic admin Password6!
Content-Type: application/json

{
  "name": "drama"
}

### delete category by id
DELETE http://localhost:8081/online-library/books-categories/202
Authorization: Basic admin Password6!