### get all borrowed
GET http://localhost:8081/api/v1/borrow
Authorization: Basic admin Password1!

### get borrow page
GET http://localhost:8081/api/v1/borrow/page?returnDateEnd=2023-08-15
Authorization: Basic admin Password1!

### add borrow
POST http://localhost:8081/api/v1/borrow/add
Authorization: Basic admin Password1!
Content-Type: application/json

{
  "customerId": 52,
  "bookId": 1
}

### get boroow by id
GET http://localhost:8081/api/v1/borrow/152
Authorization: Basic admin2 Raz12345!

### extra time borrow
PUT http://localhost:8081/api/v1/borrow/extra-time/102
Authorization: Basic admin2 Raz12345!
Content-Type: application/json

{
  "days": 30
}

### return book
PUT http://localhost:8081/api/v1/borrow/return-book/152
Authorization: Basic admin2 Raz12345!