### all types
GET http://localhost:8081/api/v1/customer-type
Authorization: Basic admin2 Raz12345!

### all types page
GET http://localhost:8081/api/v1/customer-type/page?amount=3&days=4&name=ra
Authorization: Basic admin2 Raz12345!

### add customer type
POST http://localhost:8081/api/v1/customer-type/add
Content-Type: application/json
Authorization: Basic admin2 Raz12345!

{
  "name": "raz",
  "days": 2,
  "amount": 1
}

### get type by id
GET http://localhost:8081/api/v1/customer-type/403
Authorization: Basic admin2 Raz12345!

### update type by id
PUT http://localhost:8081/api/v1/customer-type/403
Content-Type: application/json
Authorization: Basic admin2 Raz12345!

{
  "amount": 5,
  "days": 7
}

### delete type by id
DELETE http://localhost:8081/api/v1/customer-type/303
Authorization: Basic admin2 Raz12345!