### ALL cutomers
GET http://localhost:8081/api/v1/customers
Authorization: Basic admin2 Raz12345!

### get librarians page
GET http://localhost:8081/api/v1/customers/page
Authorization: Basic admin2 Raz12345!

### add customer
POST http://localhost:8081/api/v1/customers/add
Authorization: Basic admin2 Raz12345!
Content-Type: application/json

{
  "firstName": "raz",
  "lastName": "cohen",
  "email": "asdsa@gmail.com",
  "tz": "318969433",
  "phone": "0524046007",
  "address": "dsfsf",
  "customerTypeName": "raz",
  "gender": "male"
}

###get customer by id
GET http://localhost:8081/api/v1/customers/2
Authorization: Basic admin2 Raz12345!

### udpdate customer by id
PUT http://localhost:8081/api/v1/customers/2
Authorization: Basic admin2 Raz12345!
Content-Type: application/json

{
  "firstName": "raz",
  "lastName": "cohen",
  "phone": "0523561529",
  "customerTypeName": "raz"
}

### update customer - is active
PUT http://localhost:8081/api/v1/customers/active/1
Authorization: Basic admin2 Raz12345!