### ALL cutomers
GET http://localhost:8081/online-library/customers
Authorization: Basic raz 666666Raz!

### add customer
POST http://localhost:8081/online-library/customers/add
Authorization: Basic admin 666666Raz!
Content-Type: application/json

{
  "firstName": "raz",
  "lastName": "cohen",
  "email": "radfgadaa@gmail.com",
  "tz": "987654324",
  "phone": "0524046007",
  "customerTypeName": "pro"
}

###get customer by id
GET http://localhost:8081/online-library/customers/1
Authorization: Basic raz 666666Raz!