### ALL cutomers
GET http://localhost:8081/online-library/customers
Authorization: Basic raz 666666Raz!

### add customer
POST http://localhost:8081/online-library/customers/add
Authorization: Basic raz 666666Raz!
Content-Type: application/json

{
  "firstName": "raz",
  "lastName": "goanizada",
  "email": "razgoanizada@gmail.com",
  "tz": "318969432",
  "phone": "0524046007",
  "customerType": "simple"

}

###get customer by id
GET http://localhost:8081/online-library/customers/1
Authorization: Basic raz 666666Raz!