### ALL cutomers
GET http://localhost:8081/online-library/customers
Authorization: Basic simple 666666Raz!

### add customer
POST http://localhost:8081/online-library/customers/add
Authorization: Basic simple 666666Raz!
Content-Type: application/json

{
  "firstName": "raz",
  "lastName": "cohen",
  "email": "radfgdfadaa@gmail.com",
  "tz": "321321325",
  "phone": "0524046007",
  "customerTypeName": "pr"
}

###get customer by id
GET http://localhost:8081/online-library/customers/1
Authorization: Basic simple 666666Raz!