### ALL librarians
GET http://localhost:8081/online-library/librarians
Authorization: Basic admin 666666Raz!

### get librarians page
GET http://localhost:8081/online-library/librarians/page?pageNo=0&pageSize=5&sortBy=fullName&sortDir=asc
Authorization: Basic admin 666666Raz!

### add librarian
POST http://localhost:8081/online-library/librarians/add
Content-Type: application/json
Authorization: Basic admin 666666Raz!

{
  "fullName": "raz",
  "userName": "raz-admin",
  "password": "666666Raz!",
  "email": "razgoanizfada@walla.com",
  "phone": "052404607",
  "tz": "318559077",
  "permission": "simple"
}

###get librarian by id
GET http://localhost:8081/online-library/librarians/1
Authorization: Basic admin 666666Raz!

### change password
PUT http://localhost:8081/online-library/librarians/change-password/252
Content-Type: application/json
Authorization: Basic admin 666666Raz!

{
  "newPassword": "666666Raz!",
  "repeatNewPassword": "666666Raz"
}

### delete librarian by id
DELETE http://localhost:8081/online-library/librarians/602
Authorization: Basic admin 666666Raz!