### ALL librarians
GET http://localhost:8081/online-library/librarians
Authorization: Basic admin 666666Raz!

### get librarians page
GET http://localhost:8081/online-library/librarians/page?pageNo=0&pageSize=5&sortBy=fullName&sortDir=asc
Authorization: Basic admin 666666Raz!

### add librarian
POST http://localhost:8081/online-library/librarians/add
Content-Type: application/json
Authorization: Basic admin 666666Raz!

{
  "fullName": "raz goanizada",
  "userName": "simple",
  "password": "666666Raz!",
  "email": "razgoanizadaa@walla.com",
  "phone": "052404607",
  "tz": "987654324",
  "permission": "simple"
}

###get librarian by id
GET http://localhost:8081/online-library/librarians/402
Authorization: Basic admin 666666Raz!

### update librarian
PUT http://localhost:8081/online-library/librarians/302
Content-Type: application/json
Authorization: Basic admin 666666Raz!

{
  "fullName": "raz cohen ",
  "phone": "0524046007",
  "permission": "pro"
}

### change password
PUT http://localhost:8081/online-library/librarians/change-password/252
Content-Type: application/json
Authorization: Basic admin 666666Raz!

{
  "newPassword": "666666Raz!",
  "repeatNewPassword": "666666Raz!"
}

### delete librarian by id
DELETE http://localhost:8081/online-library/librarians/602
Authorization: Basic admin 666666Raz!