### all logs
GET http://localhost:8081/api/v1/logs
Authorization: Basic admin2 Raz12345!

### all logs page
GET http://localhost:8081/api/v1/logs/page?isLogin=true&username=admin&DateStart=2023-07-15
Authorization:Basic admin2 Raz12345!