### all logs
GET http://localhost:8081/api/v1/logs
Authorization: Basic admin Password1!

### all logs page
GET http://localhost:8081/api/v1/logs/page?isLogin=true
Authorization:Basic admin Password1!